services:
  # 主应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile.tencent
    image: restart-life-api:latest
    container_name: restart-life-api
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - CONFIG_ENV=docker
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs:ro
    networks:
      - restart-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  restart-network:
    driver: bridge
