server:
  port: 8080
  mode: debug
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  mysql:
    host: localhost
    port: 3306
    database: restart_life_dev
    username: root
    password: password
    charset: utf8mb4
    parse_time: true
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: 300s
    
  redis:
    host: localhost
    port: 6379
    password: ""
    database: 0
    pool_size: 10
    min_idle_conns: 3

logging:
  level: debug
  format: json
  output: stdout

auth:
  jwt_secret: "your-dev-jwt-secret-key"
  jwt_expiry: 24h
  refresh_expiry: 168h  # 7 days

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - Origin
    - Content-Type
    - Authorization
    - Accept
  allow_credentials: true

rate_limit:
  enabled: true
  requests_per_minute: 100
  burst: 50 