server:
  port: 8080
  mode: debug
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  mysql:
    host: mysql
    port: 3306
    database: restart_life_dev
    username: restart_user
    password: restart_pass
    charset: utf8mb4
    parse_time: true
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: 300s

redis:
  host: redis
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  idle_timeout: 300s

logging:
  level: debug
  format: json
  output: both
  file_path: logs/app.log
  max_size: 100
  max_backups: 5
  max_age: 7
  compress: true

cors:
  allow_origins:
    - "*"
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - "*"
  allow_credentials: true

ai:
  providers:
    - name: gemini
      api_key: your-gemini-api-key
      model_ids:
        - gemini-2.0-flash-lite
    - name: huanyuan
      api_key: your-huanyuan-api-key
      model_ids:
        - hunyuan-lite
