server:
  port: 80
  mode: release
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  version: 0.1.0

database:
  mysql:
    host: localhost
    port: 3306
    database: restart_life_live_db
    username: root
    password: password
    charset: utf8mb4
    parse_time: true
    max_open_conns: 25
    max_idle_conns: 10
    conn_max_lifetime: 300s

redis:
  host: localhost
  port: 6379
  password: ""
  database: 0
  pool_size: 20
  min_idle_conns: 5

logging:
  level: info
  format: json
  output: file
  file_path: logs/app.log
  max_size: 100 # MB
  max_backups: 5
  max_age: 7 # days
  compress: true

auth:
  jwt_secret: your-super-secret-jwt-key-change-this-in-live
  jwt_expiry: 24h
  refresh_expiry: 168h # 7 days

cors:
  allow_origins:
    - http://localhost:8080
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - Origin
    - Content-Type
    - Authorization
    - Accept
  allow_credentials: true

rate_limit:
  enabled: true
  requests_per_minute: 100
  burst: 50

ai:
  providers:
    - name: gemini
      api_key: your-gemini-api-key
      model_ids:
        - gemini-2.0-flash-lite
    - name: huanyuan
      api_key: your-huanyuan-api-key
      model_ids:
        - hunyuan-lite
