server:
  port: 8080
  mode: release
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  postgres:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    sslmode: require
    max_open_conns: 25
    max_idle_conns: 10
    conn_max_lifetime: 300s
    
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DB}
    pool_size: 20
    min_idle_conns: 5

logging:
  level: info
  format: json
  output: stdout

auth:
  jwt_secret: ${JWT_SECRET}
  jwt_expiry: 24h
  refresh_expiry: 168h  # 7 days

cors:
  allow_origins:
    - ${FRONTEND_URL}
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - Origin
    - Content-Type
    - Authorization
    - Accept
  allow_credentials: true

rate_limit:
  enabled: true
  requests_per_minute: 200
  burst: 100 